[profile.default]
src = "contracts"
test = "test"
out = "out"
solc_version = "0.6.12"
optimizer = true
optimizer_runs = 50000
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=lib/forge-std/src/"
]