[profile.default]
src = "contracts"
test = "test"
out = "out"
solc_version = "0.8.33"
optimizer = false
optimizer_runs = 200
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/@openzeppelin-contracts-4.9.3/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/@openzeppelin-contracts-upgradeable-4.9.3/contracts/"
]
